In [797]:
import numpy as np
import pandas as pd

dataframes

In [798]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A" , "B", "C"], index=["x", "y", "z"])
df.head()
# df.head(1)
# df.tail()
# df.columns
# df.index
# df.info()
# df.describe()
# df.nunique() #number unique
# df['A'].unique()
# df.shape

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

loading data from files

In [799]:
coffee = pd.read_csv('./coffee.csv')
coffee.head(8)

       day      Type  sold
0   monday  expresso    25
1   monday     latte    26
2   monday  expresso    28
3   monday     latte    29
4   monday  expresso    20
5  tuesday  expresso    26
6  tuesday     latte    23
7   monday    nestle    22

accessing data with pandas

In [800]:
# coffee # show all data
# coffee.head() # 1st five row dekh sakte h is se 10 dekhna h to (10) krdo
# coffee.tail(5) # last ke five rows dikhayega 

# coffee.loc[[0,1,5]] # 0,1,5 no. waala row dega ye , slicing ke jaisa h 
# coffee.loc[5:8 , ["day"]] 
coffee.iloc[0:5 , [0,2]]

      day  sold
0  monday    25
1  monday    26
2  monday    28
3  monday    29
4  monday    20

In [801]:
coffee.index = coffee["day"]
coffee.loc["tuesday"]

             day      Type  sold
day
tuesday  tuesday  expresso    26
tuesday  tuesday     latte    23

In [802]:
# coffee.loc[1:3 ,"sold"] = 10 # row 1 ke sold ko change kr dega aur 10 bana dega 
# coffee.head() 

#  showing error

In [803]:
# coffee.iat[0,0]
# coffee["Type"]

coffee.sort_values(["sold", "Type"],ascending=False)

             day      Type  sold
day
monday    monday     latte    29
monday    monday  expresso    28
monday    monday     latte    26
tuesday  tuesday  expresso    26
monday    monday  expresso    25
monday    monday     latte    24
tuesday  tuesday     latte    23
monday    monday    nestle    22
monday    monday     latte    21
monday    monday  expresso    20

In [804]:
for index, row in coffee.iterrows():
    print(index)
    print(row)
    print("\n\n")

monday
day       monday
Type    expresso
sold          25
Name: monday, dtype: object



monday
day     monday
Type     latte
sold        26
Name: monday, dtype: object



monday
day       monday
Type    expresso
sold          28
Name: monday, dtype: object



monday
day     monday
Type     latte
sold        29
Name: monday, dtype: object



monday
day       monday
Type    expresso
sold          20
Name: monday, dtype: object



tuesday
day      tuesday
Type    expresso
sold          26
Name: tuesday, dtype: object



tuesday
day     tuesday
Type      latte
sold         23
Name: tuesday, dtype: object



monday
day     monday
Type    nestle
sold        22
Name: monday, dtype: object



monday
day     monday
Type     latte
sold        21
Name: monday, dtype: object



monday
day     monday
Type     latte
sold        24
Name: monday, dtype: object

filtering data

In [805]:
# bios.head() # showing error

# loc

adding and removing columns

In [806]:
coffee['price']= 4.99
# coffee.head()
coffee['new_price'] = np.where(coffee['Type'] == 'expresso', 3.99, 5.99)
coffee = coffee.drop(columns=['price'] )
coffee

             day      Type  sold  new_price
day
monday    monday  expresso    25       3.99
monday    monday     latte    26       5.99
monday    monday  expresso    28       3.99
monday    monday     latte    29       5.99
monday    monday  expresso    20       3.99
tuesday  tuesday  expresso    26       3.99
tuesday  tuesday     latte    23       5.99
monday    monday    nestle    22       5.99
monday    monday     latte    21       5.99
monday    monday     latte    24       5.99

In [807]:
coffee_new = coffee
coffee_new['price']= 4.99
coffee # price add ho jaayega yaha se

             day      Type  sold  new_price  price
day
monday    monday  expresso    25       3.99   4.99
monday    monday     latte    26       5.99   4.99
monday    monday  expresso    28       3.99   4.99
monday    monday     latte    29       5.99   4.99
monday    monday  expresso    20       3.99   4.99
tuesday  tuesday  expresso    26       3.99   4.99
tuesday  tuesday     latte    23       5.99   4.99
monday    monday    nestle    22       5.99   4.99
monday    monday     latte    21       5.99   4.99
monday    monday     latte    24       5.99   4.99

In [808]:
coffee_new = coffee.copy()
coffee_new

             day      Type  sold  new_price  price
day
monday    monday  expresso    25       3.99   4.99
monday    monday     latte    26       5.99   4.99
monday    monday  expresso    28       3.99   4.99
monday    monday     latte    29       5.99   4.99
monday    monday  expresso    20       3.99   4.99
tuesday  tuesday  expresso    26       3.99   4.99
tuesday  tuesday     latte    23       5.99   4.99
monday    monday    nestle    22       5.99   4.99
monday    monday     latte    21       5.99   4.99
monday    monday     latte    24       5.99   4.99

In [809]:
coffee['revenue'] = coffee['sold'] * coffee['new_price']
coffee.rename(columns={'new_price': 'price'}) # new price ko price me rename kardega , 
# ise chalana to coffee.head ko hata dena 
# coffee.head()

             day      Type  sold  price  price  revenue
day
monday    monday  expresso    25   3.99   4.99    99.75
monday    monday     latte    26   5.99   4.99   155.74
monday    monday  expresso    28   3.99   4.99   111.72
monday    monday     latte    29   5.99   4.99   173.71
monday    monday  expresso    20   3.99   4.99    79.80
tuesday  tuesday  expresso    26   3.99   4.99   103.74
tuesday  tuesday     latte    23   5.99   4.99   137.77
monday    monday    nestle    22   5.99   4.99   131.78
monday    monday     latte    21   5.99   4.99   125.79
monday    monday     latte    24   5.99   4.99   143.76

In [ ]:
# bios_new.head()
# bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])
# bios_new.info()

# bios_new['born_year'] = bios_new['born_datetime'].dt.year
# bios_new[['name', 'born_year']]

# bios_new.to_csv('./bios_new.csv', index=False)